/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;
import lombok.extern.slf4j.Slf4j;

/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
@Slf4j
public class HelloOtus {

    public static void main(String... args) {
        List<Integer> listExample = new ArrayList<>();
        listExample.add(Integer.valueOf(1));
        listExample.add(Integer.valueOf(2));
        listExample.add(Integer.valueOf(3));
        List<Integer> reversedList = Lists.reverse(listExample);
        System.out.println(reversedList);
    }
}
